machine:
  certSANs: [${endpoint}]
  install:
    extraKernelArgs:
      - 'talos.platform=openstack'
  features:
    hostDNS:
      enabled: true
      resolveMemberNames: true
cluster:
  network:
    dnsDomain: ${cluster_domain} #
