apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: k8s-keystone-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: ${base64encode(k8s_keystone_auth_crt)}
  tls.key: ${base64encode(k8s_keystone_auth_key)}
