apiVersion: v1
kind: Service
metadata:
  name: k8s-keystone
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: k8s-keystone
  ports:
    - port: 8443
      nodePort: ${keystone_auth_port}
